name: Publish Dev Build

on:
    push:
        branches:
            - master
        paths:
            - 'packages/commandkit/**'

jobs:
    release:
        name: 🚀 Publish Dev Build
        runs-on: ubuntu-latest
        steps:
            - uses: pnpm/action-setup@v2
              with:
                  version: 8

            - name: 📚 Checkout
              uses: actions/checkout@v3

            - name: 🟢 Node
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org

            - name: 🍳 Prepare
              run: pnpm install

            - name: 🔢 Update Version
              run: |
                  cd packages/commandkit
                  node -e "const pkg = require('./package.json'); \
                  const newVersion = pkg.version + '-dev.' + new Date().toISOString().replace(/[:\-T]/g, '').substr(0,14); \
                  pkg.version = newVersion; \
                  require('fs').writeFileSync('./package.json', JSON.stringify(pkg, null, 2));"
              env:
                  DEBIAN_FRONTEND: noninteractive

            - name: 🚚 Publish
              run: pnpm run deploy:package-dev
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
